# Generated by Django 5.0.2 on 2025-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_options_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Tiene descuento'),
        ),
    ]
